### ISSUE TITLE
Captcha bypass

### ISSUE THREAD

**Issue by opalav8** [55chan/55chan#1]
8chan captcha suffers from a problem: the characters used for captcha are fetched from a variable that may be controlled by user input. This is obviously a security flaw that allows a malicious user to bypass captcha.
This is where the vulnerability resides:
https://github.com/55chan/55chan/blob/master/8chan-captcha/entrypoint.php#L20

It means that a user can manipulate captcha to get whatever he wants. A step-by-step on how to reproduce is:
- Try to start a thread, wait for the captcha to appear but do not fill it.
- Access `/8chan-captcha/entrypoint.php?mode=get&extra=a `.
- Go back to the captcha and fill it with "aaaaaaaa".

**Comment by john-clever** [comment]
I'll check it out.
